import requests
import json

url = "https://job.xiaohongshu.com/websiterecruit/apply/apply"

headers = {
    "accept": "application/json, text/plain, */*",
    "accept-encoding": "gzip, deflate, br, zstd",
    "accept-language": "zh-CN,zh;q=0.9",
    "authorization": "NGE1ODc3NTJlZWY3NGE1YTkzMjU5MWI2Nzg0OTE3YzM=",  # 请替换为最新值
    "content-type": "application/json",
    "cookie": "abRequestId=e5f91265-5009-5ccd-8a54-9142a30b050c; a1=19a2a4c66c8c827y8b05xmnvfc3aht4s4n9pqn6cf50000413101; webId=5090d456e07b3731d57a1727f40d8ed0; gid=yj0J04DKj84jyj0J04SKKIIKSYSYJWvYD82CjSi6IhiSqU280x94MA8884yqy8y8j8qYY0Sy; web_session=0400698f01a38756e3663f60223b4bb0828b82; ets=1774503508876; webBuild=6.2.2; unread={%22ub%22:%2269c261100000000021004c13%22%2C%22ue%22:%2269a3e8c9000000000d0098e2%22%2C%22uc%22:54}; xsecappid=ats-website; acw_tc=0a0d01fc17746268286686805e8bee0dda8941f99e4921e779a7b9054fedeb; loadts=1774627567235; websectiga=9730ffafd96f2d09dc024760e253af6ab1feb0002827740b95a255ddf6847fc8; sec_poison_id=a1ce3877-1ebe-43ce-afaa-84ada5a6b969",  # 请替换为最新值
    "origin": "https://job.xiaohongshu.com",
    "priority": "u=1, i",
    "referer": "https://job.xiaohongshu.com/campus/position/19192/apply",  # 注意 referer 中的 positionId 可能需要对应调整
    "sec-ch-ua": '"Chromium";v="146", "Not-A.Brand";v="24", "Microsoft Edge";v="146"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36 Edg/146.0.0.0",
    "x-b3-traceid": "65f28336d20f27cc",
    "x-s": "XYS_2UQhPsHCH0c1PjhhHjIj2erjwjQY4oPT49pjq9SF8aHVHdWUH0ijp9S18BR7qUHVHdWAH0ijJnEAPerIPpRyqe8D2ep38aTtzbzyqbbbnaReL741pFQzPBb/ydzO/DR/4oSHPDk9LMqA8fk38MHU4dY14BSHt9peLS+IPdD3tFI9J94/cFVELMkhGLVl+9k/4rRt8fV3PFzhzgSPqeG9t9RByM+gpeQE4Bb9anMB8eSBP0YytFi3+D8a2nSkLnlbJBbsyFYBLpz1y0QjwnT/87i6nd8VwbmLcFMt8gzSJDlEyfhFarYfwnPjNsQh+sHCHfRjyfp04sQR",  # 请替换为最新值
    "x-s-common": "2UQAPsHC+aIjqArjwjHjNsQhPsHCH0rjNsQhPaHCH0c1PjhhHjIj2eHjwjQgynEDJ74AHjIj2ePjwjQY4oPT49pjq9SF8aHVHdWFH0ijPahIN0rjNsQh+aHCH0rEG/QY+BP9+fPhGAWU+7DhG0ZM2BM14f80P9bi4ezA+BhEqob1+f+f+/ZIPeZFP/PlPerjNsQh+jHCHjHVHdW7H0ijHjIj2eWjwjQQPAYUaBzdq9k6qB4Q4fpA8b878FSet9RQzLlTcSiM8/+n4MYP8F8LagY/P9Ql4FpUzfpS2BcI8nT1GFbC/L88JdbFyrSiafp/8BThqgb78rS9cg+gcf+i4MmF4B4T+e8NpgkhanWIqAmPa7+xqg412/4rnDS9J7+hGSmx2pkMcLSia9prG/4A8SpLprkl4bH3qg4mqBzI/DSeyBMwa/YN2S87LFSe89p34gzH47b7zrSbzdbQzaRAprSyyLShqDMQ4f4S8ob7LjV7qbmCnDEA8bDA8n8l4rbQyFESPM8787bl4omI4gzha7kdqAbgqBpQcM8ganYzPsRc4bbNpd4ma/+yPfRT8Bpkqg4faL+m8pzn4oQQzaV3aLpTJf+f8Bpx87k8qfR6q98l4FRyp9RS8rlrzrQ687+xndmsagYNq9zn4BbQy78S8db7LfQ+/rSo80zsa/P7q7Yl4rL6pFRS2emV+rSiLg+Qz/W3LnzypLShJpmO2fM6anS0nBpc4F8Q4fSePDQ9qFzC+7+hpdzDagG98nc7+9p8ySQoanSD8/8gGDcUpd4xanYtqA+68gP9zo8SpbmF/f+p+fpr4gqMag8887km+npDqg4mqBG6q98c47QQPMc6agYTJo+l4o+YLo4Eq7+HGSkm4fLAqsRSzbm72rSe8g+3zemSL9pHyLSk+7+xGfRAP94UzDSk8BL94gqAanSUy7zM4BMF4gzBagYS8pzc4r8QyrkSyp8FJrS389LILoz/t7b7Lokc4MpQ4fY3agY0q0zdarr3aLESypmFyDSiqdzQyBRAydbFLrlILnb7qDTA8B808rSi2juU4g4yqdp7LFSe8o+3Loz/tFMN8/b0cg+LzflEanYwq7WE+7+3LozoJdp7/FSePBpgqg4banV98p8SpFlQc9zSng+98p+l4eSQPA4Apdp74L4dLnbQzgQNagG6q9TPPBpL808SzrcAqFzn4BRQypmia/+LnoQn4bbQ4f+iaLpwqA+BqLb7NURAL7pFGLS3LdQT4gclz7kw8LzyPo+/4gz687pFJLDAzBQQzLL38pmF8pmM4URQ2o8ApfF78pzM4UT04gc3anYjwBpn4bmQypzTarSM2rDA8oPAqo8AyL8d8Lzc47YTqgzmagYg8rS3J7+8qgzpanYw8nz/LfTQcFp9GS48JFSeyFRQ40pS+db7yeQn4BEzLozVa/+PprSkcg+3pAFRHjIj2eDjw0WM+eqIP/c9PaIj2erIH0iINsQhP/rjwjQ1J7QTGnIjKc==",  # 请替换为最新值
    "x-t": "1774628122585"  # 请替换为最新值
}

payload = {
    "applyType": "campus",
    "accountId": 601451,
    "positionId": 15615,
    "positionName": "Java后端开发实习生",
    "jobProjectName": None,
    "positionWorkplace": "北京市，上海市",
    "jobTypeDesc": "后端开发",
    "talentId": 1636204,
    "interviewId": 6447401,
    "status": "resume_choose_doing",
    "interviewStatusColor": "#00000073",
    "resumeId": 10077482,
    "resumeUrl": "https://ep-ehr-s1.xhscdn.com/recruit/1040g28g31u7a6l2lgu0000000000ibbb224a7s0.pdf?sign=3afdbd14b95776b074b7652e339601e1&t=69c7974f",
    "resumeName": "枚子君-Java后端开发实习生-简历",
    "attachmentUrl": None,
    "attachmentName": None,
    "name": "枚子君",
    "mobile": "+86 17773045931",
    "email": "2544431082@qq.com",
    "gender": None,
    "adaptable": True,
    "applyTime": "2026-03-28T00:27:58.000+0800",
    "birthday": "2002-06",
    "workplaceIntentionList": [
        "3100",
        "1100"
    ],
    "highestEducation": "硕士研究生",
    "highestEducationCollege": "南京大学",
    "graduationDate": "2027-06",
    "resumeVo": {
        "resumeId": 10077482,
        "resumeName": "枚子君-Java后端开发实习生-简历",
        "name": "枚子君",
        "gender": None,
        "age": 24,
        "birthday": "2002-06",
        "mobile": "+86 17773045931",
        "email": "2544431082@qq.com",
        "graduationDate": "2027-06",
        "workYears": 1,
        "undergraduateCollegeName": None,
        "highestEducation": "硕士研究生",
        "highestEducationCollege": "南京大学",
        "highestEducationMajor": "软件工程",
        "selfEvaluation": None,
        "jobIntention": "研发实习",
        "workplaceIntention": "上海市,北京市",
        "salaryIntention": None,
        "recentCompany": "苏宁易购集团股份有限公司",
        "recentJob": "java开发",
        "resumeUrl": "https://ep-ehr-s1.xhscdn.com/recruit/1040g28g31u7a6l2lgu0000000000ibbb224a7s0.pdf?sign=3afdbd14b95776b074b7652e339601e1&t=69c7974f",
        "resumeInfo": None,
        "attachmentUrl": None,
        "resumeContent": None,
        "createTime": None,
        "publications": [],
        "publicationDesc": None,
        "awards": [],
        "awardDesc": None,
        "workLink": None,
        "githubStar": None,
        "certificates": [],
        "avatarUrl": "https://xhs-ehr-static.xhscdn.com/uinfocollect/ats_avatar_98dbc6a05bfe494d80f803955016302f.jpg",
        "resumeEducationInfo": [
            {
                "resumeId": 10077482,
                "schoolName": "南京大学",
                "schoolRank": 0,
                "schoolType": 0,
                "startDate": "2025-09",
                "endDate": "2027-06",
                "isTongzhao": True,
                "major": "软件工程",
                "majorRank": 0,
                "toPresent": False,
                "gpa": None,
                "eduNature": None,
                "degree": "硕士研究生",
                "collegeName": None,
                "city": "南京",
                "country": "中国",
                "internationalRanking": 0,
                "province": "江苏",
                "tags": "985",
                "level": "985",
                "id": 19193761,
                "normalizedSchoolName": "南京大学",
                "laboratory": "",
                "researchDirection": "",
                "scoreRank": "",
                "mentor": "",
                "setSchoolName": True,
                "setSchoolRank": True,
                "setSchoolType": True,
                "setIsTongzhao": True,
                "setMajor": True,
                "setMajorRank": True,
                "setToPresent": True,
                "setGpa": False,
                "setEduNature": False,
                "setDegree": True,
                "setCity": True,
                "setCountry": True,
                "setInternationalRanking": True,
                "setProvince": True,
                "setLevel": True,
                "setNormalizedSchoolName": True,
                "setLaboratory": True,
                "setResearchDirection": True,
                "setScoreRank": True,
                "setMentor": True,
                "setId": True,
                "setTags": True,
                "setStartDate": True,
                "setEndDate": True,
                "setResumeId": True,
                "setCollegeName": False
            },
            {
                "resumeId": 10077482,
                "schoolName": None,
                "schoolRank": 0,
                "schoolType": 0,
                "startDate": "2020-09",
                "endDate": "2024-06",
                "isTongzhao": True,
                "major": "计算机科学与技术",
                "majorRank": 0,
                "toPresent": False,
                "gpa": None,
                "eduNature": None,
                "degree": "本科",
                "collegeName": None,
                "city": None,
                "country": None,
                "internationalRanking": 0,
                "province": None,
                "tags": None,
                "level": None,
                "id": 19193762,
                "normalizedSchoolName": None,
                "laboratory": "",
                "researchDirection": "",
                "scoreRank": "",
                "mentor": "",
                "setSchoolName": False,
                "setSchoolRank": True,
                "setSchoolType": True,
                "setIsTongzhao": True,
                "setMajor": True,
                "setMajorRank": True,
                "setToPresent": True,
                "setGpa": False,
                "setEduNature": False,
                "setDegree": True,
                "setCity": False,
                "setCountry": False,
                "setInternationalRanking": True,
                "setProvince": False,
                "setLevel": False,
                "setNormalizedSchoolName": False,
                "setLaboratory": True,
                "setResearchDirection": True,
                "setScoreRank": True,
                "setMentor": True,
                "setId": True,
                "setTags": False,
                "setStartDate": True,
                "setEndDate": True,
                "setResumeId": True,
                "setCollegeName": False
            }
        ],
        "resumeEmploymentInfo": [
            {
                "resumeId": 10077482,
                "companyName": "苏宁易购集团股份有限公司",
                "title": "java开发",
                "department": None,
                "industry": None,
                "jobNature": None,
                "category": "专业技术人员>后端开发>软件工程师",
                "toPresent": False,
                "startDate": "2024-08",
                "endDate": "2024-11",
                "salary": None,
                "jobAchieve": None,
                "jobResp": None,
                "description": None,
                "city": "南京",
                "jobLocation": None,
                "reasonForLeaving": None,
                "id": 32071431,
                "normalizedCompanyName": "苏宁易购集团股份有限公司",
                "rank": "",
                "leader": "",
                "subordinates": 0,
                "aliasName": "",
                "promote": False,
                "performance": "",
                "xhsDepartmentId": 0,
                "setToPresent": True,
                "setCity": True,
                "setCompanyName": True,
                "setDepartment": False,
                "setIndustry": False,
                "setSalary": False,
                "setJobAchieve": False,
                "setJobResp": False,
                "setDescription": False,
                "setJobLocation": False,
                "setReasonForLeaving": False,
                "setNormalizedCompanyName": True,
                "setLeader": True,
                "setSubordinates": True,
                "setPromote": False,
                "setXhsDepartmentId": True,
                "setId": True,
                "setStartDate": True,
                "setEndDate": True,
                "setResumeId": True,
                "setRank": True,
                "setCategory": True,
                "setJobNature": False,
                "setTitle": True,
                "setAliasName": True,
                "setPerformance": True
            },
            {
                "resumeId": 10077482,
                "companyName": "杭州默安科技有限公司",
                "title": "测试实习生",
                "department": None,
                "industry": None,
                "jobNature": "实习",
                "category": "专业技术人员>质量管理>测试工程师,专业技术人员>前端开发>游戏工程师",
                "toPresent": False,
                "startDate": "2024-01",
                "endDate": "2024-03",
                "salary": None,
                "jobAchieve": None,
                "jobResp": None,
                "description": None,
                "city": "杭州",
                "jobLocation": None,
                "reasonForLeaving": None,
                "id": 32071432,
                "normalizedCompanyName": "杭州默安科技有限公司",
                "rank": "",
                "leader": "",
                "subordinates": 0,
                "aliasName": "",
                "promote": False,
                "performance": "",
                "xhsDepartmentId": 0,
                "setToPresent": True,
                "setCity": True,
                "setCompanyName": True,
                "setDepartment": False,
                "setIndustry": False,
                "setSalary": False,
                "setJobAchieve": False,
                "setJobResp": False,
                "setDescription": False,
                "setJobLocation": False,
                "setReasonForLeaving": False,
                "setNormalizedCompanyName": True,
                "setLeader": True,
                "setSubordinates": True,
                "setPromote": False,
                "setXhsDepartmentId": True,
                "setId": True,
                "setStartDate": True,
                "setEndDate": True,
                "setResumeId": True,
                "setRank": True,
                "setCategory": True,
                "setJobNature": True,
                "setTitle": True,
                "setAliasName": True,
                "setPerformance": True
            }
        ],
        "resumeProjectInfo": [
            {
                "resumeId": 10077482,
                "company": None,
                "projectName": "忆存云图",
                "description": "基于spring boot+redis+cos+ai+websocket的智能图片存储与管理平台,为企业和个人提供图片存储、智能检索与协作服务。地址:http://118.195.165.9/,仓库名:pictureplatform",
                "responsibility": "1)权限管理:基于sa-token的kit模式实现了多账号体系的rbac权限控制;\n2)以图搜图:通过jsoup和httpclient2获取百度以图搜图api,运用门面模式组合api调用获取图片列表,方便用户使用;\n3)多级缓存:利用redis+caffeine设计多级缓存架构,响应耗时降低400%,并通过随机过期降低缓存雪崩事件;\n4)协同编辑:基于websocket+事件驱动实现用户间图片的实时协作编辑;\n5)优化协同编辑方案:引入disruptor优化高并发场景下的异步任务处理,利用redis和rabbitmq实现扩展到分布式多实例的方案;\n6)智能搜索模块:搭建python agent模块,搭建milvus向量数据库,实现基于ai多模态的智能搜索功能;将java中的核心服务包装为mcp,供python agent灵活调用;",
                "startDate": "2025-11",
                "endDate": "2026-01",
                "id": 19520241,
                "role": None,
                "setCompany": False,
                "setResponsibility": True,
                "setDescription": True,
                "setId": True,
                "setStartDate": True,
                "setEndDate": True,
                "setResumeId": True,
                "setProjectName": True,
                "setRole": False
            },
            {
                "resumeId": 10077482,
                "company": None,
                "projectName": "轻量级llm推理框架",
                "description": "一个用于深入理解现代大模型推理系统核心机制的项目。python实现的简化版vllm。",
                "responsibility": "基于pytorch+triton通过简短的代码实现vllm的核心机制:pagedattention,continuousbathching, prefill+decode 并行等,在rtx5060显卡上适配minimind模型(教学用小模型)并达到vllm推理速度。",
                "startDate": "2025-10",
                "endDate": "2025-11",
                "id": 19520242,
                "role": None,
                "setCompany": False,
                "setResponsibility": True,
                "setDescription": True,
                "setId": True,
                "setStartDate": True,
                "setEndDate": True,
                "setResumeId": True,
                "setProjectName": True,
                "setRole": False
            },
            {
                "resumeId": 10077482,
                "company": None,
                "projectName": "tripgenius",
                "description": "基于ai与大模型的智能旅行规划与管理系统,支持智能行程规划、费用追踪与实时旅行\n辅助。采用python+flask+supabase+openaiapi技术栈。仓库名:web_travel_agent",
                "responsibility": "独立完成从前端、后端、第三方服务对接到docker容器化部署的全流程开发。",
                "startDate": "2025-10",
                "endDate": "2025-10",
                "id": 19520243,
                "role": None,
                "setCompany": False,
                "setResponsibility": True,
                "setDescription": True,
                "setId": True,
                "setStartDate": True,
                "setEndDate": True,
                "setResumeId": True,
                "setProjectName": True,
                "setRole": False
            }
        ],
        "resumePaperInfo": [],
        "resumeAwardInfo": [],
        "resumePatentInfo": [],
        "resumeSkillInfo": [],
        "resumeTrainingInfo": [],
        "resumeHashInfo": [],
        "resumeLanguageInfo": [],
        "resumeCampusWorkInfo": [],
        "resumeCertificateInfo": [],
        "previewResumeUrl": "https://ep-ehr-s1.xhscdn.com/recruit/1040g28g31u7a6l2lgu0000000000ibbb224a7s0.pdf?sign=3afdbd14b95776b074b7652e339601e1&t=69c7974f",
        "internEntryDateDesc": "1周内",
        "internshipTimeDesc": "6个月以上",
        "internDayPerWeek": 5,
        "internEntryDate": "one_week",
        "internshipTime": "more_than_six_months"
    },
    "tags": None,
    "order": 0,
    "interviewStatusDesc": "简历初筛(进行中)",
    "orderStr": None
}

response = requests.post(url, headers=headers, json=payload, timeout=30)
print("Status Code:", response.status_code)
print("Response Body:", response.text)